version: "3"
services:
  hmpps-historical-prisoner-indexer:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-historical-prisoner-indexer
    depends_on:
      - localstack
      - hmpps-auth
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  localstack:
    image: localstack/localstack:0.12.10
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - 8999:8080
    environment:
      - SERVICES=sqs,sns,es,elasticsearch
      - ES_PORT_EXTERNAL=4571
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

  iis-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
networks:
  hmpps:
