---
# Per environment values which override defaults in hmpps-historical-prisoner-indexer/values.yaml

generic-service:
  ingress:
    host: historical-prisoner-indexer.prison.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
